# Site settings
title: Eric.Zhang的个人博客
email: net.eric.zhang@gmail..com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://neteric.github.io" # the base hostname & protocol for your site


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tag'


# Social account
# twitter:  username
# weibo:    ID
# github:   username
# codepen:  username
# dribbble: username


# Google Analytics
# google_analytics: tracking_ID


# Build settings
# 语法高亮
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
 
 #博文的链接样式
permalink: /:year-:month-:day-:title.html

# title 图标
#favicon: /assets/images/favicon.ico
#

# 博客作者相关
author:
  name: neteric
  email: net.eric.zhang@gmail.com
  link: http://neteric.github.io/
  github: https://github.com/neteric
  github_username: neteric

locals:
  tags: 标签
  about: 关于
  active: 技术
subscribe_rss: /pages/atom.xml

# 头像
avatar: /assets/images/avatar.jpg
# avatar: http://7xpapo.com1.z0.glb.clouddn.com/blog/assets/image/favicon.ico
# 网站CSS路径
css: /assets/css/
# css: http://7xpapo.com1.z0.glb.clouddn.com/blog/assets/css/
# 网站JS路径
js: /assets/js/
# js: http://7xpapo.com1.z0.glb.clouddn.com/blog/assets/js/
# 网站图片路径
image: /assets/image/
# image: http://7xpapo.com1.z0.glb.clouddn.com/blog/assets/image/

# disqus 设置
disqus:
  shortname: ericzhang
